### ISSUE TITLE
Wet_BFL_Dur is the same as Wet_Tim_Water Metric on https://eflows.ucdavis.edu/profile

### ISSUE THREAD

**Issue by kklausmeyer** [leogoesger/func-flow#119]
**Describe the bug**
When I run the functional flows calculator via the https://eflows.ucdavis.edu/profile page and I download the "Annual Flow Result" the resulting .csv file includes the same data for both the Wet_BFL_Dur and the Wet_Tim_Water metrics.  In comparing with the python version, I believe that Wet_Tim_Water is correct, meaning the Wet_BFL_Dur data is missing

**To Reproduce**
1. Go to https://eflows.ucdavis.edu/profile
2. Download the sample data (https://s3-us-west-1.amazonaws.com/funcflow/resources/sample.csv)
3. Click on 'Pick a File' and upload the sample data
4. Add a name
4. Click on the "Upload" button
5. In the result area, download the "Annual Flow Result
6. Open in excel

**Expected behavior**
I expect the data to be different for the Wet_BFL_Dur and the Wet_Tim_Water metrics.

**Screenshots**
![image](https://user-images.githubusercontent.com/11560493/110373495-68b74d80-8004-11eb-9a48-0c6ab960221d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by kklausmeyer** [comment]
Note this is a known issue with a fix here:  https://github.com/leogoesger/eflow-client/pull/97

**Comment by leogoesger** [comment]
Thanks, fixed.
